version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: uniElasticSearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - action.destructive_requires_name=false
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: uniKibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    container_name: uniLogstash
    ports:
      - "5000:5000"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk
  mongodb:
    image: mongo:7.0
    container_name: uniMongoDB
    restart: always
    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: notification_db
    volumes:
      - mongo_data:/data/db
    networks:
      - elk


  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: uniMongoExpress
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true

    depends_on:
      - mongodb
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  mongo_data: